# See https://feathericons.com/
# The value of 'pre' is the icon name

main:
- identifier: home
  name: Home
  pre: home
  url: /
  weight: 1
# - identifier: about
#   name: About
#   pre: smile
#   url: /about/
#   weight: 20
# - identifier: history
#   name: History
#   parent: about
#   pre: smile
#   url: /history/
#   weight: 21
# - identifier: admissions-concessions
#   name: Admissions & Concessions
#   pre: clipboard
#   url: /admissionconcessions/
#   weight: 10
# - name: Tags
#   pre: tag
#   url: /tags
#   weight: 13
# - name: RSS
#   pre: rss
#   url: /index.xml
#   weight: 25