includeBootstrapJs: true
showActiveNav: true
containerMaxWidth: 1800px
dateFormat: Jan 2, 2006
# homeText: We are closed tonight (January 12) due to travel not advised. Please stay safe and check back tomorrow for further updates.
homeText: The Wieting's schedule is subject to change without notice. Please check often for updates!
# homeText: Our equipment is working again so we will be showing last weekend's feature twice on Sunday, July 14. We won't be able to fully test the repairs until just before showtime on Sunday afternoon, so keep your fingers crossed for us.  See ya' at the Wieting!
footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
hideFooter: false
katex: false
customCss: "css/custom.css"
dropboxURL: ""

social:
  share:
    donate:
      switch: true
      url: "/donate"
    facebook:
      switch: true
      url: "https://www.facebook.com/WietingTheatre/"
    linkedin:
      switch: false
    # twitter:
    #   switch: true
    #   url: "https://twitter.com/WietingTheatre"
    whatsapp:
      switch: false
    email:
      switch: true
      url: "mailto:ToledoWieting@gmail.com"
