baseURL: https://wieting.tamatoledo.com/
languageCode: en-us
title: The Wieting Theatre
theme: vanilla-bootstrap-hugo-theme
socialshare: true
paginate: 40
timeZone: America/Chicago
disableKinds: [ "RSS" ]
# disableKinds: [ "section", "RSS" ]

# googleAnalytics: UA-194668720-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# Fullcalendar elements
buildFuture: true
publishDir: "dist"

outputs:
  section: 
    - HTML
    - JSON
